[build]
  base    = ""
  publish = "/build"

[context.production]
  publish = "build/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "15.8.0", NPM_VERSION = "7.6.0" }

[[redirect]]
from = "/*"
to = "/index.html"
status = 200