[build]
  base    = ""
  publish = "/build"

[context.production.environment]
  NODE_VERSION = "15.8.0"

[context.deploy-preview.environment]
  NODE_VERSION = "15.8.0"

[[redirect]]
from = "/*"
to = "/index.html"
status = 200